### ISSUE TITLE
Ajuda getCertificadoKeyStore()

### ISSUE THREAD

**Issue by henriqueneves** [wmixvideo/bradesco-boleto-registro#3]
Olá, tudo bom?

Você tem um exemplo da implementação do método getCertificadoKeyStore() para emissão de boletos? 

Li na documentação do Bradesco que o padrão de assinatura é o PKCS#7, então o exemplo que tem na NFe (PKCS12) não funciona.

Queria um exemplo só pra entender como retornar uma KeyStore trabalhando com o PKCS7.

Obrigado

**Comment by fincatto** [comment]
Usamos o 12, sem problemas. 
Inclusive, o método é igualzinho ao da NFe. 
Testa aí que deve funcionar!
Att
