### ISSUE TITLE
Erro genérico código no retorno do envio

### ISSUE THREAD

**Issue by KaueMre** [wmixvideo/bradesco-boleto-registro#4]
Tento fazer o envio, parece que funciona, já que antes ele me alegou erros de layout no preenchimento de alguns campos, mas agora me retorna esse erro:

"cdErro":"2", "msgErro":"Erro"

Estou sem muitas idéias de como resolver, se for ver no próprio layout diz que é um erro genérico:

02 Erro Genérico – sistema indisponível

Cogitei tambem a possiblidade de ser o erro -2, que seria:

-2 Contrato não encontrado

Caso seja ele, observei que o numero de contrato seria o proprio cnpj, nesse caso o preenchimento é:

nuCPFCNPJ : São os 8 primeiros digitos do cnpl, só que o espaço é para 9 digitos, coloca um antes para completar?
filialCPFCNPJ : São 4 digitos, no caso do cnpj deve iniciar com os 000 ou deve ter só os digitos relevantes, "1" ou "0001"
Não sei se o problema pode ser algo disso que ja´tentei todas as variações possiveis.

Estou preso a isso e não consigo avançar, mais alguem teve esse problema, ou conhece a solução?

**Comment by fincatto** [comment]
Boa tarde. Funciona sim, usamos em produção a meses. É uma lib, não tem
classe principal. Vide manual do Bradesco.

**Comment by deluxeuo** [comment]
@fincatto obrigado pelo retorno.
Eu fiquei na dúvida mesmo é de como chamar o WS
 **public RegistroRetornoBoleto enviarBoleto(final BBRConfig config, final RegistroEntradaBoleto registroEntrada)** 

A dúvida maior é como montar o objeto BBRConfig, por causa dos certificados. 
Voce tem um exemplo dessa chamada?

Obrigado

**Comment by fincatto** [comment]
Eu estou em viagem agora, somente com o celular. Mas veja nosso projeto da
NF-e que tem um exemplo no readme.
