### ISSUE TITLE
Duvida na implementação de BBRConfig

### ISSUE THREAD

**Issue by machap** [wmixvideo/bradesco-boleto-registro#5]
Olá, muito obrigado por compartilhar esse projeto.

Estou com uma duvida na implementação do BBRConfig, pois no método 

`getCadeiaCertificadosKeyStore()` não consigo encontra o utilitário 

`NFGeraCadeiaCertificados.geraCadeiaCertificados(NFAmbiente.PRODUCAO, "senha"))`  .

Sou bem leigo nesse assunto, e preciso realizar uma rotina de envio boleto ao Bradesco. 

Caso você tenha algum exemplo de implementação dessa classe poderia postar, pra mim vê como você lê os certificados Keystore também? Fico muito agradecido.

**Comment by fincatto** [comment]
Boa tarde Paulo.
Você pode encontrar exemplos de implementação neste projeto:
https://github.com/wmixvideo/nfe
Não tem relação um com o outro, mas a idéia é a mesma.
Att

**Comment by fincatto** [comment]
Pode estar relacionado sim, mas não tenho como ter certeza.
Eu tenho ele implementado, conforme exemplo da NFe, e estou rodando há
meses, sem problemas.
Att

**Comment by machap** [comment]
@fincatto agradeço pela ajuda e por compartilhar esse projeto. Finalmente conseguir fazer o envio. Muito grato.
